# Site settings
name: Do you ever Djent?
email: scorpionsand@163.com
author: Peijie Chen
url: 
resume_site: https://github.com/MarkChanxDjent/CV/blob/master/CV_Peijie_Chen.pdf
github: https://github.com/MarkChanxDjent
baseurl: "/MarkChanxDjent.github.io"
description: 捧哏艺术家
meta_description: 
motto: Do you ever Djent bro?
banner: So we roll the dice.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: MarkChanxDjent

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9


theme: jekyll-theme-architect
